<?php

/*
 * This file is licensed under GPLv2+.
*/

/**
 * @file
 * Provides the basic information of signup program, such as provinces and nationalities.
 */

/**
 * Implementation of hook_help().
 */
function essential_help($path, $arg) {
  return;
}

function essential_init() {
	drupal_add_js(drupal_get_path('module', 'essential') .'/jquery.placeholder.js');
	drupal_add_js(
		'jQuery(document).ready(function(){'.
			'jQuery(":input[placeholder]").placeholder();'.
		'});',
		'inline'
	);

	drupal_add_js(drupal_get_path('module', 'essential') .'/jQuery.dPassword.js');
	/*
	if(!empty($_SERVER['HTTP_USER_AGENT']) && (!preg_match('/Mobile/', $_SERVER['HTTP_USER_AGENT']) && !preg_match('/Windows NT 6.1/', $_SERVER['HTTP_USER_AGENT'])) )
	drupal_add_js(
		'jQuery(document).ready(function(){'.
			'if(jQuery("input:password").length>0)'.
			'jQuery("input:password").dPassword();'.
		'});',
		'inline'
	);*/
}


/**
 * Implementation of province load helper function.
 */
function province_load($pid) {
	return db_select('vl_province','p')->condition('p.pid',$pid)->fields('p')->execute()->fetchObject();
}

/**
 * Implements hook_block_info().
 */
function essential_block_info() {
	$result=array();
	
	$result['weather'] = array(
		'info' => t('Weather'),
		'cache' => DRUPAL_CACHE_GLOBAL,
	);
	return $result;
}

/**
 * Implements hook_block_view().
 */
function essential_block_view($delta = '') {
	global $user;
	$block = array();
	switch ($delta) {
		case 'weather':
			$options=array('timeout'=>1);
			$valid_code=array('302','200');
			$r=json_decode(variable_get('current_weather',''))->weatherinfo;
			if($r===FALSE) return;
			$block['subject'] = t('Weather of @city',array('@city'=>$r->city));
			$c=($r->fchh>=15?'n':'d');
			$period=($r->fchh>=15?t('night to tomorrow day'):t('day to night'));
			$img=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/21x15/%s%02d.gif" title="%s">', $c,$r->img1, $r->img_title1);
			$c=($r->fchh>=15?'d':'n');
			$img.=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/21x15/%s%02d.gif" title="%s">&nbsp;', $c,($r->img2==99?$r->img1:$r->img2), $r->img_title2);
			$block['content'] = '<b>'.t('This @period',array('@period'=>$period)).'</b><br/>'.$img.$r->weather1.' '.$r->temp1;
			$block['content'].= '<br/>';
			$c=($r->fchh>=15?'n':'d');
			$period=($r->fchh>=15?t('night to the day after tomorrow day'):t('day to night'));
			$img=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/21x15/%s%02d.gif" title="%s">', $c, $r->img3, $r->img_title3);
			$c=($r->fchh>=15?'d':'n');
			$img.=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/21x15/%s%02d.gif" title="%s">&nbsp;', $c, ($r->img4==99?$r->img3:$r->img4), $r->img_title4);
			$block['content'].= '<b>'.t('Tomorrow @period',array('@period'=>$period)).'</b><br/>'.$img.$r->weather2.' '.$r->temp2;
			$block['content'].= '<br/>';
			$c=($r->fchh>=15?'n':'d');
			$img=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/21x15/%s%02d.gif" title="%s">', $c,$r->img5, $r->img_title5);
			$c=($r->fchh>=15?'d':'n');
			$period=($r->fchh>=15?t('night to the next day'):t('day to night'));
			$img.=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/21x15/%s%02d.gif" title="%s">&nbsp;', $c,($r->img6==99?$r->img5:$r->img6), $r->img_title6);
			$block['content'].= '<b>'.t('The day after tommorrow @period',array('@period'=>$period)).'</b><br/>'.$img.$r->weather3.' '.$r->temp3;
	}
	return $block;
}

/**
 * Implements hook_cron().
 */
function essential_cron() {
	$options=array('timeout'=>1);
	$valid_code=array('302','200');
	do {
		$r=drupal_http_request("http://m.weather.com.cn/data/101010100.html",$options);
	} while ($r->code !='200');
	variable_set('current_weather', $r->data);
}

function essential_username_alter(&$name, $account) {
	if($account->uid==1) $name=t('Administrator');
	$query=db_select('vl_research_sec','r')->condition('uid',$account->name)->fields('r',array('rname'));
	$r=$query->execute()->fetchObject();
	if($r)
		$name=$r->rname;
}
