<?php

/*
 * This file is licensed under GPLv2+.
*/

/**
 * @file
 * Provides the basic information of signup program, such as provinces and nationalities.
 */

/**
 * Implementation of hook_help().
 */
function essential_help($path, $arg) {
  return NULL;
}

/**
 * Implementation of hook_menu().
 */
function essential_menu() {
}

/**
 * Implements hook_block_info().
 */
function essential_block_info() {
	$result=array();
	
	$result['weather'] = array(
		'info' => t('Weather'),
		'cache' => DRUPAL_NO_CACHE
	);
	return $result;
}

/**
 * Implements hook_block_view().
 */
function essential_block_view($delta = '') {
	global $user;
	$block = array();
	switch ($delta) {
		case 'weather':
			$r=drupal_http_request('http://m.weather.com.cn/data/101010100.html');
			if($r->code='302') {
				$r=json_decode($r->data)->weatherinfo;
				$block['subject'] = t('Weather of @city',array('@city'=>$r->city));
				$img=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/29x20/d%02d.gif" title="'.$r->img_title1.'"/>',$r->img1);
				$img.=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/29x20/n%02d.gif" title="'.$r->img_title2.'"/>&nbsp;',($r->img2==99?$r->img1:$r->img2));
				$block['content'] = t('Today: ').$img.$r->weather1.' '.$r->temp1;
				$block['content'].= '<br/>';
				$img=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/29x20/d%02d.gif" title="'.$r->img_title3.'"/>',$r->img3);
				$img.=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/29x20/n%02d.gif" title="'.$r->img_title4.'"/>&nbsp;',($r->img4==99?$r->img3:$r->img4));
				$block['content'].= t('Tomorrow: ').$img.$r->weather2.' '.$r->temp2;
				$block['content'].= '<br/>';
				$img=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/29x20/d%02d.gif" title="'.$r->img_title5.'"/>',$r->img5);
				$img.=sprintf('&nbsp;<img src="http://www.weather.com.cn/m2/i/icon_weather/29x20/n%02d.gif" title="'.$r->img_title6.'"/>&nbsp;',($r->img6==99?$r->img5:$r->img6));
				$block['content'].= t('The day after tommorrow: ').$img.$r->weather3.' '.$r->temp3;
			}
	}
	return $block;
}
